export type VillageLesson = {
  id: string
  label: string
  focus: string
  goal: string
  text: string
}

export type VillageContent = {
  lessons: VillageLesson[]
  capstone: VillageLesson
  wordBank: string[]
}

export const meadowFarm: VillageContent = {
  lessons: [
    {
      id: 'meadow-farm-l01',
      label: 'First Furrow',
      focus: 'home row — left hand (asdf)',
      goal: 'Find the home keys without looking.',
      text: 'add all ask dad fad lad sad fall falls flask lads lass dads fads asks flasks salads add all ask',
    },
    {
      id: 'meadow-farm-l02',
      label: 'Even Ground',
      focus: 'home row — right hand (jkl;)',
      goal: 'Let the right hand settle into its keys.',
      text: 'jj kk ll ;; jk kj jl lj j; ;j jkl lkj ;lk jjk kkl ll; ;;j jk kl l; ;j jkl lkj jj kk ll ;;',
    },
    {
      id: 'meadow-farm-l03',
      label: 'Full Row',
      focus: 'home row — both hands together',
      goal: 'Keep both hands calm and unhurried.',
      text: 'ask a lad; fall all flasks; a sad lass asks; dads fall; all lads add falls; flask falls all;',
    },
    {
      id: 'meadow-farm-l04',
      label: 'Word Flow I',
      focus: 'home-row words — short and common',
      goal: 'Type real words at a steady, unhurried pace.',
      text: 'add ads all ask dad fad fall flask lad lass sad salad asks dads fads falls lads flasks salads all',
    },
    {
      id: 'meadow-farm-l05',
      label: 'Word Flow II',
      focus: 'home-row words — slightly longer',
      goal: 'Stay smooth as the words grow a little longer.',
      text: 'salads flasks lads lass dads fads falls asks all add sad fad dad flask lad salad fall all adds ask',
    },
    {
      id: 'meadow-farm-l06',
      label: 'Rhythm Drill I',
      focus: 'repeated words with comma pauses',
      goal: 'Let repetition build confidence in each word.',
      text: 'fall fall fall; ask ask ask; add add add; all all all; sad sad sad; lad lad lad; dad dad dad; fad;',
    },
    {
      id: 'meadow-farm-l07',
      label: 'Rhythm Drill II',
      focus: 'two-word pairs repeated',
      goal: 'Keep the same easy pace through paired repetition.',
      text: 'fall all; fall all; ask dad; ask dad; sad lad; sad lad; add flask; add flask; all lass; all lass;',
    },
    {
      id: 'meadow-farm-l08',
      label: 'Home Row Phrase I',
      focus: 'short phrases with punctuation',
      goal: 'Hit the semicolon key cleanly without breaking rhythm.',
      text: 'all fall; ask a lad; dads fall; sad lass asks; a flask falls; all lads ask dads; falls all; ask;',
    },
    {
      id: 'meadow-farm-l09',
      label: 'Home Row Phrase II',
      focus: 'longer phrases across full row',
      goal: 'Read ahead and let the phrase carry your pace.',
      text: 'a sad lad asks all dads; all fall flasks shall last; flask falls; a glad lass adds all; ask all;',
    },
    {
      id: 'meadow-farm-l10',
      label: 'Steady Hands I',
      focus: 'sentence drill — deliberate pace',
      goal: 'Accuracy above all — let every key land cleanly.',
      text: 'all glad lads fall; a sad lass asks all dads; fall all flasks shall last a full fall; ask a lass;',
    },
    {
      id: 'meadow-farm-l11',
      label: 'Steady Hands II',
      focus: 'sentence drill — longer lines',
      goal: 'Hold the steady pace to the end of each line.',
      text: 'a flask of salad dressing falls; all sad dads ask all lads; a glad lass adds fads to all flasks;',
    },
    {
      id: 'meadow-farm-l12',
      label: 'Left Hand Lock',
      focus: 'left hand (asdf) intensive',
      goal: 'Drill the left hand until each key feels certain.',
      text: 'add fad dad sad all fall flask ask adds fads dads sads falls flasks asks alfalfa salad salads add',
    },
    {
      id: 'meadow-farm-l13',
      label: 'Right Hand Lock',
      focus: 'right hand (jkl;) intensive',
      goal: 'Give the right hand its own uninterrupted practice.',
      text: 'jj kk ll ;; jkl lkj ;lk kl; l;j jk kl lk; ;jk jjkk kkll ll;; ;;jj jklk lkj; j;kl kljj ;j kl',
    },
    {
      id: 'meadow-farm-l14',
      label: 'Crossing Hands',
      focus: 'alternating left-right keys',
      goal: 'Keep both hands independent without letting one rush the other.',
      text: 'af jd sk l; af jd sk l; fj dk sl ;a fj dk sl ;a fjdk dksl slaf fjdk dksl slaf fj dk sl ;a fj',
    },
    {
      id: 'meadow-farm-l15',
      label: 'Flask and Fall',
      focus: 'f and l keys with surrounding context',
      goal: 'Feel how f and l anchor their hands in real words.',
      text: 'fall flask falls flasks alfalfa fall flask all fall flask falls alfalfa flask fall flask falls all',
    },
    {
      id: 'meadow-farm-l16',
      label: 'Ask and Add',
      focus: 'a, s, d — left-hand trio',
      goal: 'Move smoothly across the three left-hand fingers.',
      text: 'ask add ads ask add ads asks adds dads dads asks adds ask a sad dad; adds asks dads sad ask add;',
    },
    {
      id: 'meadow-farm-l17',
      label: 'Lad and Lass',
      focus: 'l, a, d, s — real words in flow',
      goal: 'Keep pace through short familiar words.',
      text: 'lad lass lads lass lad lads all lad lass lads all falls lad lass lads sad lad lass lads all fall',
    },
    {
      id: 'meadow-farm-l18',
      label: 'Salad Days',
      focus: 'longer home-row words',
      goal: 'Stretch the fingers through longer words without hesitating.',
      text: 'salad salads alfalfa salad salads alfalfa salad adds flask falls lads salads all salad alfalfa all',
    },
    {
      id: 'meadow-farm-l19',
      label: 'Phrase Flow I',
      focus: 'natural phrase rhythm',
      goal: 'Let the phrase guide your pace instead of thinking key by key.',
      text: 'ask all dads; all lads fall; a sad lass adds fads; flask falls; all dads ask all lads; fall all;',
    },
    {
      id: 'meadow-farm-l20',
      label: 'Phrase Flow II',
      focus: 'varied phrase length',
      goal: 'Adjust smoothly as phrases shift from short to long.',
      text: 'all fall; a flask; ask a lass; all lads fall; a sad dad asks all; flask falls; add all fads; ask;',
    },
    {
      id: 'meadow-farm-l21',
      label: 'Double Trouble',
      focus: 'doubled letters — aa ss dd ff jj kk ll',
      goal: 'Land both presses of each double cleanly without bouncing.',
      text: 'add all fad fall lass dads flask fads all add lass fall dads fads flask falls salad adds all fall;',
    },
    {
      id: 'meadow-farm-l22',
      label: 'Speed Burst I',
      focus: 'short words at a brisk pace',
      goal: 'Let the short words roll off the fingers faster than usual.',
      text: 'fad sad lad dad ask all add fall fads lads dads asks adds falls all fad sad lad dad ask all add;',
    },
    {
      id: 'meadow-farm-l23',
      label: 'Speed Burst II',
      focus: 'medium words at increased pace',
      goal: 'Chase a slightly higher speed without dropping accuracy.',
      text: 'flask falls lads lass dads fads salad asks flasks falls lads lass dads fads salad asks flask falls;',
    },
    {
      id: 'meadow-farm-l24',
      label: 'Sentence Drill I',
      focus: 'complete sentences with semicolons',
      goal: 'Type a full thought from start to full stop.',
      text: 'a sad dad falls; all lads ask; flask falls; a glad lass adds all fads; ask all dads; falls all;',
    },
    {
      id: 'meadow-farm-l25',
      label: 'Sentence Drill II',
      focus: 'longer complete sentences',
      goal: 'Hold focus to the end of every longer sentence.',
      text: 'all glad lads shall ask all sad dads; a flask falls and all lass dads add fads; ask all; fall all;',
    },
    {
      id: 'meadow-farm-l26',
      label: 'Mixed Bag',
      focus: 'random home-row word order',
      goal: 'Stay ready for any word — no pattern to lean on.',
      text: 'lass fall ask dads add all fad flask lad salad sad lads fads asks falls flask salads alfalfa dads;',
    },
    {
      id: 'meadow-farm-l27',
      label: 'The Long Field',
      focus: 'extended line without pause',
      goal: 'Cover a longer stretch without losing your place.',
      text: 'add all ask a dad; fall flask falls; lads ask all dads; sad lass falls; all fads add; flask falls;',
    },
    {
      id: 'meadow-farm-l28',
      label: 'Punctuation Run',
      focus: 'semicolons woven through every phrase',
      goal: 'Keep the right pinky relaxed through every semicolon.',
      text: 'ask; add; all; fall; flask; lads; lass; dads; fads; sad; lad; dad; fad; ask; fall; adds; flask;',
    },
    {
      id: 'meadow-farm-l29',
      label: 'Alfalfa Field',
      focus: 'alfalfa and salad — longest home-row words',
      goal: 'Stretch smoothly without choking on the longer reach.',
      text: 'alfalfa salads alfalfa salads all flask falls alfalfa salad adds all lads alfalfa salads flask fall',
    },
    {
      id: 'meadow-farm-l30',
      label: 'Final Field',
      focus: 'everything together — full home row fluency',
      goal: 'Show that the home row feels like home.',
      text: 'all dads ask all lads; a sad lass falls; flask falls; add all fads; alfalfa salads; asks fall all;',
    },
  ],

  capstone: {
    id: 'meadow-farm-capstone',
    label: 'Harvest Check',
    focus: 'full home row rhythm at a confident pace',
    goal: 'Prove the home row feels natural — fingers settled, pace steady.',
    text: 'a glad lad shall ask a lass; all fall tasks shall last a full fall; sad dads add all flasks; ask a lass all fads fall; all lads shall ask all dads; flask falls; a salad shall last; alfalfa falls;',
  },

  wordBank: [
    'add all ask dad fad lad sad fall falls flask lads lass dads fads asks flasks salads add all ask dad',
    'all fall; ask a lad; dads fall; sad lass asks; a flask falls; all lads ask dads; falls all; asks;',
    'fall fall fall; ask ask ask; add add add; all all all; sad sad sad; lad lad lad; dad dad dad; fad;',
    'a sad lad asks all dads; all fall flasks shall last; flask falls; a glad lass adds all; ask all;',
    'all glad lads fall; a sad lass asks all dads; fall all flasks shall last a full fall; ask a lass;',
    'salad salads alfalfa salad salads alfalfa salad adds flask falls lads salads all salad alfalfa all;',
    'ask all dads; all lads fall; a sad lass adds fads; flask falls; all dads ask all lads; fall all;',
    'all fall; a flask; ask a lass; all lads fall; a sad dad asks all; flask falls; add all fads; ask;',
    'lass fall ask dads add all fad flask lad salad sad lads fads asks falls flask salads alfalfa dads;',
    'ask; add; all; fall; flask; lads; lass; dads; fads; sad; lad; dad; fad; ask; fall; adds; flask;;',
    'alfalfa salads alfalfa salads all flask falls alfalfa salad adds all lads alfalfa salads flask fall',
    'all dads ask all lads; a sad lass falls; flask falls; add all fads; alfalfa salads; asks fall all;',
    'fad sad lad dad ask all add fall fads lads dads asks adds falls all fad sad lad dad ask all add;',
    'flask falls lads lass dads fads salad asks flasks falls lads lass dads fads salad asks flask falls;',
    'a sad dad falls; all lads ask; flask falls; a glad lass adds all fads; ask all dads; falls all;;',
    'all glad lads shall ask all sad dads; a flask falls and all lass dads add fads; ask all; fall all;',
    'fall flask falls flasks alfalfa fall flask all fall flask falls alfalfa flask fall flask falls all;',
    'ask add ads ask add ads asks adds dads dads asks adds ask a sad dad; adds asks dads sad ask add;',
    'lad lass lads lass lad lads all lad lass lads all falls lad lass lads sad lad lass lads all fall;',
    'add all fad fall lass dads flask fads all add lass fall dads fads flask falls salad adds all fall;',
    'af jd sk l; af jd sk l; fj dk sl ;a fj dk sl ;a fjdk dksl slaf fjdk dksl slaf fj dk sl ;a fj dk',
    'add fad dad sad all fall flask ask adds fads dads falls flasks asks alfalfa salad salads add all;',
    'jj kk ll ;; jkl lkj ;lk kl; l;j jk kl lk; ;jk jjkk kkll ll;; ;;jj jklk lkj; j;kl kljj ;j kl;',
    'a flask of salad falls; all sad dads ask all lads; a glad lass adds fads to all flasks; ask all;',
    'all dads fall; all lads ask; a flask falls; sad lass asks; add all fads; ask a dad; flask falls;',
    'add all ask a dad; fall flask falls; lads ask all dads; sad lass falls; all fads add; flask falls;',
    'fj dk sl ;a jf kd ls ;a fj dk sl ;a fj dk sl ;a jf kd ls ;a fj dk sl ;a fj dk sl ;a jf kd ls;',
    'all fall flasks; lads ask all lass; a sad dad adds; flask falls; all salads fall; ask all dads;',
    'sad fad lad dad add all ask fall flask lass lads fads dads salad asks falls flasks salads all add;',
    'ask a glad lad; all flasks fall; a lass adds all; sad dads fall; a flask of salad; all lads ask;',
    'ff jj ff jj dd kk dd kk ss ll ss ll aa ;; aa ;; fj dk sl a; fj dk sl a; ff jj dd kk ss ll aa ;;',
    'fj jf fj jf dk kd dk kd sl ls sl ls a; ;a a; ;a fj jf dk kd sl ls a; ;a fj jf dk kd sl ls a;;',
    'all glad lads add; a flask falls; sad lass asks all dads; fall all; adds fads; ask a lad; falls;',
    'flask falls; all lads ask; a sad lass adds all fads; dads ask; flask falls; all add; ask all lass;',
    'add a salad; all lads fall; ask a sad dad; flask falls; a lass asks all; add all fads; falls all;',
    'alfalfa and salads fall; a flask falls; all lads ask all dads; sad lass adds all; flask falls all;',
    'dad ask all; fall all; flask falls; lass asks; lads add; sad fad; all dads fall; ask a glad lad;',
    'fj dk sl a; all dads ask; fall flask falls; lads lass dads fads; sad lad dad fad; asks all; fall;',
    'a sad lass falls; all flask falls; ask all dads; lads add fads; flask falls; ask a glad dad; all;',
    'add all; ask a dad; fall flask; all lads; lass asks; sad dads; fads fall; salad falls; alfalfa all',
    'ask all glad dads; fall flask falls; all lads add; a sad lass falls; ask a dad; flask falls; all;',
    'all dads and lads ask all sad lass; flask falls; a salad falls; all fads fall; ask all; alfalfa;',
    'fall all flasks; ask all lads; a sad dad adds; all lass falls; flask falls; add all fads; asks all',
    'lads and lass ask all dads; flask falls; a glad lad adds all; sad dads fall; ask a lass; all fall;',
    'ask ask ask; fall fall fall; all all all; add add add; lad lad lad; dad dad dad; flask flask flask;',
    'sad all ask; flask lads fall; lass dads add; fads fall; all flasks ask; salad lads; alfalfa falls;',
    'a flask falls; all lads ask dads; a sad lass falls; add all fads; ask all; flask falls; all dads;',
    'all fall flasks shall last; ask all glad lads; a sad lass adds all; flask falls; alfalfa salads all',
    'fall all; ask all; add all; lad all; dad all; fad all; lass all; flask all; salad all; alfalfa all',
    'a glad lad shall ask a lass; all fall tasks shall last; sad dads add all flasks; asks fall; all;',
  ],
}
